/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Container: typeof import('./src/components/container.vue')['default']
    CustomPage: typeof import('./src/components/customPage.vue')['default']
    SubContainer: typeof import('./src/components/subContainer.vue')['default']
  }
}
